# Generated by Django 6.0.4 on 2026-04-16 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_before', models.ImageField(upload_to='work_proofs/before/')),
                ('photo_after', models.ImageField(upload_to='work_proofs/after/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_proofs', to='Snow.posting')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_proofs', to='Snow.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
