# Generated by Django 6.0.4 on 2026-04-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snow', '0002_workproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
