# Generated by Django 6.0.4 on 2026-04-16 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snow', '0003_posting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXIFMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field_name', models.CharField(choices=[('photo_before', 'Before photo'), ('photo_after', 'After photo')], help_text='Which image this EXIF data belongs to.', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in metres.', null=True)),
                ('camera_make', models.CharField(blank=True, max_length=120)),
                ('camera_model', models.CharField(blank=True, max_length=120)),
                ('datetime_original', models.DateTimeField(blank=True, help_text='Date/time the photo was originally taken.', null=True)),
                ('orientation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('software', models.CharField(blank=True, max_length=200)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_exif', models.JSONField(blank=True, default=dict)),
                ('work_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exif_entries', to='Snow.workproof')),
            ],
            options={
                'verbose_name': 'EXIF metadata',
                'verbose_name_plural': 'EXIF metadata',
                'unique_together': {('work_proof', 'image_field_name')},
            },
        ),
    ]
