apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soen357-db
  namespace: soen357
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soen357-media
  namespace: soen357
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
